/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ows_kotlinstudy_ndk_build_MainActivity */

#ifndef _Included_ows_kotlinstudy_ndk_build_MainActivity
#define _Included_ows_kotlinstudy_ndk_build_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ows_kotlinstudy_ndk_build_MainActivity
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ows_kotlinstudy_ndk_1build_MainActivity_plus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ows_kotlinstudy_ndk_build_MainActivity
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ows_kotlinstudy_ndk_1build_MainActivity_minus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ows_kotlinstudy_ndk_build_MainActivity
 * Method:    multi
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ows_kotlinstudy_ndk_1build_MainActivity_multi
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ows_kotlinstudy_ndk_build_MainActivity
 * Method:    div
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_ows_kotlinstudy_ndk_1build_MainActivity_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
